site_name: Zynq-7000 JTAG Tool
site_description: Low-level JTAG and QSPI Flash interaction tool for Xilinx Zynq-7000.

docs_dir: doc

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search
  - mkdocstrings:
        handlers:
          python:
            paths: ['src']

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js

nav:
  - Home: index.md
  - Project Architecture: architecture.md
  - JTAG Protocol Basics: jtag_basics.md
  - FTDI MPSSE Engine: mpsse_protocol.md
  - ARM Coresight: arm_coresight.md
  - FSBL Injection: fsbl_injection.md
  - API Reference: api_reference.md